---
- id: fish_syntax
  name: Fish syntax check
  description: Check Fish shell syntax
  entry: fish --no-execute
  language: system
  types: [fish]

- id: fish_indent_lint
  name: Fish indent check
  description: Check Fish shell indentation
  entry: pre-commit-hooks/fish_indent_lint.fish
  language: script
  types: [fish]

- id: fish_indent_format
  name: Fish indent format
  description: Format fish syntax
  entry: pre-commit-hooks/fish_indent.fish
  language: script
  types: [fish]
